In [6]:
#Define Python Library
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [8]:
#For Test
#read the image file
im = Image.open('cat.jpg')
pix = np.array(im)
height = im.size[1]
width = im.size[0]
print("Size :", width ,"x", height)

Size : 180 x 180


In [9]:
#For Test
#make 3-dimension RGB data
numpy_array = np.array(im, dtype="uint8")
print(numpy_array)

[[[204 212 215]
  [204 212 215]
  [204 212 215]
  ...
  [202 207 211]
  [202 207 211]
  [202 207 211]]

 [[203 211 214]
  [204 212 215]
  [204 212 215]
  ...
  [202 207 211]
  [202 207 211]
  [202 207 211]]

 [[203 211 214]
  [203 211 214]
  [203 211 214]
  ...
  [202 207 211]
  [202 207 211]
  [202 207 211]]

 ...

 [[182 175 146]
  [187 178 149]
  [182 173 144]
  ...
  [150  53  94]
  [150  53  96]
  [150  53  96]]

 [[162 155 129]
  [173 163 138]
  [174 164 139]
  ...
  [149  52  93]
  [149  52  95]
  [149  52  95]]

 [[116 108  87]
  [128 117  97]
  [129 118  96]
  ...
  [149  52  93]
  [149  52  95]
  [149  52  95]]]


In [10]:
#For Test
#convert 3-dimension RGB data into 1-dimension
flatten_numpy_array = np.ravel(numpy_array, order='C')
print(flatten_numpy_array)

[204 212 215 ... 149  52  95]


In [11]:
#For Test
#save txt file of rgb data of picture
np.savetxt("cat_rgb_data", flatten_numpy_array)

In [12]:
#load txt data
loaded_array = np.loadtxt("cat_rgb_data",dtype='uint8')

C:\Users\ask_m\AppData\Local\Temp\ipykernel_20320\3899484097.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  loaded_array = np.loadtxt("cat_rgb_data",dtype='uint8')


In [13]:
#reshape flatten data into 3-dimension
print("######################")
reshaped_numpy_array = loaded_array.reshape(height,width,3)
#print(reshaped_numpy_array)

######################


In [14]:
myimage = Image.fromarray(reshaped_numpy_array, 'RGB')
myimage.show()